services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: apptest
    restart: unless-stopped
    volumes:
      - ./web:/web
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.app.entrypoints=http"
      - "traefik.http.routers.app.rule=Host(`app.domain.tld`)"
      - "traefik.http.services.app.loadbalancer.server.port=80"
      - "traefik.docker.network=proxy"
      # HTTPS
      - "traefik.http.routers.app-secure.entrypoints=https"
      - "traefik.http.routers.app-secure.rule=Host(`app.domain.tld`)"
      - "traefik.http.routers.app-secure.tls=true"
      - "traefik.http.routers.app-secure.tls.options=cloudflare-mtls@file"
      - "traefik.http.routers.app-secure.service=app"

networks:
  proxy:
    external: true
