services:
  adguard:
    image: adguard/adguardhome:latest
    container_name: adguard-home
    restart: unless-stopped
    networks:
      - proxy
    volumes:
      - ./work:/opt/adguardhome/work
      - ./conf:/opt/adguardhome/conf
    labels:
      # AdGuard Home Dashboard and DNS over HTTPS
      - "traefik.enable=true"
      - "traefik.http.routers.adguard.entrypoints=http"
      - "traefik.http.routers.adguard.rule=Host(`dns.domain.tld`)"
      - "traefik.http.middlewares.adguard-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.adguard.middlewares=adguard-https-redirect"
      - "traefik.http.routers.adguard-secure.entrypoints=https"
      - "traefik.http.routers.adguard-secure.rule=Host(`dns.domain.tld`)"
      - "traefik.http.routers.adguard-secure.tls=true"
      - "traefik.http.routers.adguard-secure.service=adguard-dashboard"
      - "traefik.http.services.adguard-dashboard.loadbalancer.server.port=80"
      - "traefik.docker.network=proxy"

      # DoT service
      - "traefik.tcp.services.adguard-dot-service.loadbalancer.server.port=53"
      # TCP Router for DNS-over-TLS (DoT)
      - "traefik.tcp.routers.adguard-dot.entrypoints=dot"
      - "traefik.tcp.routers.adguard-dot.rule=HostSNI(`dns.domain.tld`) || HostSNIRegexp(`^.+\\.dns\\.domain\\.tld$`)"
      - "traefik.tcp.routers.adguard-dot.tls=true"
      - "traefik.tcp.routers.adguard-dot.service=adguard-dot-service"

networks:
  proxy:
    external: true
